alter function auth_branch_ids() set search_path = public, pg_temp;
alter function auth_business_id() set search_path = public, pg_temp;
alter function auth_business_ids() set search_path = public, pg_temp;
alter function auth_role() set search_path = public, pg_temp;
alter function current_db_time() set search_path = public, pg_temp;
alter function has_permission(text) set search_path = public, pg_temp;
alter function is_platform_admin() set search_path = public, pg_temp;
alter function my_memberships() set search_path = public, pg_temp;
alter function prevent_profile_self_privilege_escalation() set search_path = public, pg_temp;
alter function require_active_business() set search_path = public, pg_temp;
alter function set_business_slug() set search_path = public, pg_temp;
alter function set_default_active_business() set search_path = public, pg_temp;
alter function set_owner_request_reference_code() set search_path = public, pg_temp;
alter function slugify(text) set search_path = public, pg_temp;
alter function switch_active_business(uuid) set search_path = public, pg_temp;
alter function touch_updated_at() set search_path = public, pg_temp;
alter function user_has_permission(uuid, text) set search_path = public, pg_temp;
revoke all on function audit_debt_changes() from public, anon, authenticated;
revoke all on function prevent_profile_self_privilege_escalation() from public, anon, authenticated;
revoke all on function set_default_active_business() from public, anon, authenticated;
revoke all on function has_permission(text) from public, anon;
revoke all on function user_has_permission(uuid, text) from public, anon;
revoke all on function my_memberships() from public, anon;
revoke all on function switch_active_business(uuid) from public, anon;
revoke all on function create_receipt_share(uuid) from public, anon;
grant execute on function has_permission(text) to authenticated;
grant execute on function user_has_permission(uuid, text) to authenticated;
grant execute on function my_memberships() to authenticated;
grant execute on function switch_active_business(uuid) to authenticated;
grant execute on function create_receipt_share(uuid) to authenticated;
